/// Flutter icons FacebookIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FacebookIcon
///      fonts:
///       - asset: fonts/FacebookIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FacebookIcon {
  FacebookIcon._();

  static const _kFontFam = 'FacebookIcon';
  static const String? _kFontPkg = null;

  static const IconData facebook_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
